name: Unit Testing

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:

  test:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck jq

    - name: Setup Docker
      uses: docker/setup-buildx-action@v3

    - name: Lint shell scripts
      run: |
        shellcheck scripts/*.sh

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Format Check
      run: terraform fmt -check -recursive

    - name: Terraform Init
      working-directory: terraform
      run: terraform init -backend=false

    - name: Terraform Validate
      working-directory: terraform
      run: terraform validate

    - name: Install BATS
      run: |
        git clone https://github.com/bats-core/bats-core.git
        sudo ./bats-core/install.sh /usr/local

    - name: Deploy infrastructure
      run: | 
        chmod +x scripts/deploy.sh
        sudo scripts/deploy.sh --auto-install --non-interactive

    - name: Run Bash tests
      run: bats tests/

    - name: Get exposed ports
      run: |
        terraform -chdir=terraform show -json \
          | jq -r '.values.root_module.resources[]
          | select(.type=="docker_container")
          | .values.ports[].external' \
          | sort -u > ports.txt

    - name: Destroy infrastructure
      working-directory: terraform
      run: terraform destroy -auto-approve
